---
- hosts: all
  user: ubuntu
  sudo: yes
  roles:
    - ubuntu-common
    - imagemagick
    - chruby
    - ruby-install
    - role: build-ruby
      version: 2.3.0
    - role: nginx-unicorn
      nginx_sites:
        - name: 'production'
          server_name: '_'
          root: '/home/ubuntu/skynet/current'
          listen: '0.0.0.0:80'
          access_log:
            format: 'combined'
