---
galaxy_info:
  author: Andrew Angelo Ang
  description: Installs chruby on Ubuntu systems.
  company: InnoHub, Inc.
  license: MIT
  min_ansible_version: 1.4
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - trusty
  categories:
    - development
    - system
dependencies: []
