---
:concurrency: 50
:pidfile: tmp/pids/sidekiq.pid
:queues:
  - [screener, 64]
  - [recorder, 32]
  - [mapper, 16]
  - [sitemapper, 8]
  - [scrimper, 4]
  - [sampler, 2]
  - [spider, 1]
  - default
:limits:
  screener: 1
  sitemapper: 1
  scrimper: 5
  sampler: 5
  spider: 5
