---
:concurrency: 3
:pidfile: tmp/pids/sidekiq.pid
:queues:
  - [screener, 64]
  - [uploader, 32]
  - [retreader, 16]
  - [scrimper, 8]
  - [sampler, 4]
  - [spider, 2]
  - [sitemapper, 1]
  - default
:limits:
  screener: 1
  sitemapper: 1
