---
:concurrency: 1
:pidfile: tmp/pids/sidekiq.pid
:queues:
  - [screener, 264]
  - [recorder, 128]
  - [mapper, 64]
  - [slider, 32]
  - [scrimper, 16]
  - [socializer, 8]
  - [sampler, 4]
  - [spider, 2]
  #- [sitemapper, 1]
  - default
