---
:concurrency: 10
:pidfile: tmp/pids/sidekiq.pid
:queues:
  #- [screener, 128]
  - [recorder, 64]
  - [mapper, 32]
  - [slider, 16]
  - [scrimper, 8]
  - [sampler, 4]
  - [spider, 2]
  #- [sitemapper, 1]
  - default
