---
:concurrency: 5
:pidfile: tmp/pids/sidekiq.pid
:queues:
  - [screener, 64]
  - [recorder, 32]
  - [mapper, 16]
  - [sitemapper, 8]
  - [scrimper, 4]
  - [sampler, 2]
  - [spider, 1]
  - default
:process_limits:
  sitemapper: 1
  screener: 1
  scrimper: 2
  sampler: 2
  spider: 2
  mapper: 5
