galaxy_info:
  author: AR
  description: common setup routine for ubuntu
  license: MIT
  min_ansible_version: 1.2
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - trusty
  categories:
  - system
dependencies: []
