---
galaxy_info:
  author: Alex Wilson
  description: Ansible role to create sqlite databases
  license: MIT
  min_ansible_version: 1.4
  categories:
  - database
  - database:sql
  platforms:
  - name: Fedora
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all
dependencies: []
