---
- name: check-parameters
  include: checkParameters.yml
  tags:
      - check
- name: os-specific vars
  include_vars: "{{ansible_os_family}}.yml"
  tags:
      - always
- include: java.yml
  tags:
      - java
- include: elasticsearch.yml
  tags:
      - install
- include: elasticsearch-config.yml
  tags:
      - config
- include: elasticsearch-scripts.yml
  when: es_scripts
  tags:
      - scripts
- include: elasticsearch-plugins.yml
  when: es_plugins is defined or es_plugins_reinstall
  tags:
      - plugins
- include: elasticsearch-service.yml
  tags:
      - service
- include: elasticsearch-templates.yml
  when: es_templates
  tags:
      - templates
- meta: flush_handlers
