---
galaxy_info:
  author: Alexandros Giouzenis
  description: Nginx installation with Unicorn integration
  license: MIT
  min_ansible_version: 1.2
  platforms:
  - name: EL
    versions:
    - all
  - name: Fedora
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all
  categories:
  - system
  - web
dependencies: []

